---
- name: Small playbook to test that credentials can be grabbed from HashiCorp Vault
  hosts: localhost 
  tasks:
    - name: Create a file to a directory
      file: 
       path: "/home/jamieh/test.txt"
       state: touch
