---
- name: Small playbook to test that credentials can be grabbed from HashiCorp Vault
  hosts: localhost
  vars_files:
    - vars.yml 
  tasks:
  - name: Get API access token
    uri:
      url: "https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token"
      method: POST
      return_content: True
      body_format: form-urlencoded
      headers:
        accept: application/json
      body:
        grant_type: refresh_token
        client_id: rhsm-api
        refresh_token: '{{ my_offline_token }}'
      validate_certs: False
    register: access_token_reponse

  - name: Print access API access token
    set_fact:
      token: '{{ access_token_reponse.json.access_token }}'

  - name: Print it
    debug:
      var: token
